# Numpy


### Numpy and its 5 functions

Numpy is a Python library which used for working on arrays. Its fucntions are also used in working on linear algebra and matrices. Here are the 5 out of many fucntions in Numpy:-

- `numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")`
- `numpy.reciprocal(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'reciprocal'>`
- `numpy.unravel_index(indices, shape, order='C')` 
- `numpy.tile(A, reps)`
- `numpy.pad(arr, pad_width, mode='constant', **kwargs)` 

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [6]:
function1 = np.concatenate    # It is used to concatenate two arrays into one along a particular existing axis
function2 = np.reciprocal     # It is used to return the reciprocal of the argument, element-wise.
function3 = np.unravel_index  # It is used to convert a flat index or array of flat indices into a tuple of coordinate arrays.
function4 = np.tile           # It is used to construct an array by repeating A the number of times given by reps.
function5 = np.pad            # It is used to pad an array

In [8]:
function1, function2, function3, function4, function5

(<function numpy.concatenate>,
 <ufunc 'reciprocal'>,
 <function numpy.unravel_index>,
 <function numpy.tile(A, reps)>,
 <function numpy.pad(array, pad_width, mode='constant', **kwargs)>)

## Function 1 - np.concatenate

It is used to join two arrays into one along a particular existing axis

In [10]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2) , axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

> In this example two arrays `arr1` and `arr2` are joined along the columns due to `axis=1` property.

In [9]:
# Example 2 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2) , axis=None)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

> In this example, with `axis=None` property the arrays are joined  but are flattened.



In [11]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

> In this example `axis=0` property is used which means that arrays are     intended to be joined along the rows but the no of columns in both the arrays are not same which give us the error. To remove this error simply increase the no of columns of smaller array.




>When you want to join arrays , you can this function but keep in mind that while using `axis=0` property, no of coulmns in arrays must be same. Similarily while using `axis=1` property, no of rows in arrays must be same. 



## Function 2 - np.reciprocal

It is used to return the reciprocal of the argument, element-wise.

In [12]:
# Example 1 - working
np.reciprocal([2., 3., 5., 6.])

array([0.5       , 0.33333333, 0.2       , 0.16666667])

> It can be clearly seen from the example that it returns the reciprocal of the elements in the array.



In [13]:
# Example 2 - working
np.reciprocal([[2., 4., 22., 6., 91.],
              [4.1, 5.3, 4.22, 1.09, 7.99]])

array([[0.5       , 0.25      , 0.04545455, 0.16666667, 0.01098901],
       [0.24390244, 0.18867925, 0.23696682, 0.91743119, 0.12515645]])

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
np.reciprocal([2, 4, 22, 6, 91]), np.reciprocal([0, 0, 0])

<ipython-input-14-eb9509866363>:2: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal([2, 4, 22, 6, 91]), np.reciprocal([0, 0, 0])
<ipython-input-14-eb9509866363>:2: RuntimeWarning: invalid value encountered in reciprocal
  np.reciprocal([2, 4, 22, 6, 91]), np.reciprocal([0, 0, 0])


(array([0, 0, 0, 0, 0], dtype=int32),
 array([-2147483648, -2147483648, -2147483648], dtype=int32))

> It displays 0 for all the elements of first array because all of them are integers and this fucntion does not work on integers. Hence their reciprocal is 0.

> Also, on the array containing 0, it displays a RunTimeWarning as it cannont find the reciprocal of zero

>So when you want to find the recipriocal of arrays containg `float` type numbers, you can use this `numpy.reciprocal` function.





## Function 3 - np.unravel_index

It is used to convert a flat index or array of flat indices into a tuple of coordinate arrays.

In [15]:
# Example 1 - working
np.unravel_index(100, (6,7,8), order='F')

(4, 2, 2)

> In the above example, function `np.unravel_index` finds the index of 100th element in the array of size (6, 7, 8) and displays it in column-major style because of `order='F'` property.



In [16]:
# Example 2 - working
np.unravel_index(100, (6,7,8), order='C')

(1, 5, 4)

>In the above example, function `np.unravel_index` finds the index of 100th element in the array of size (6, 7, 8) and displays it in row-major style because of `order='C'` property. It is different from the example 1.

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
np.unravel_index(np.array([]), (6,7,8))

TypeError: only int indices permitted

> In the above, example we are getting a `TypeError` because `[]` in numpy is a `float` value by default and `float` indices are not permitted. To avoid getting this error, use `np.array([], dtype='int')` instead of `np.array([])`

> So , when you want to find out the index of $nth$ element in a $(i, j, k)$ shaped array , u can use this function

 ## Function 4 - np.tile

It is used to construct an array by repeating A the number of times given by reps.

In [18]:
# Example 1 - working
np.tile(np.array([1, 3, 5 ,6]) , reps=5)

array([1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6])

> In the above example, the array is reapeated 5 times in one direction

In [19]:
# Example 2 - working
np.tile(np.array([1, 3, 5, 6]), reps=(3,3,3,3))

array([[[[1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6]],

        [[1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6]],

        [[1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6]]],


       [[[1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6]],

        [[1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6]],

        [[1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6]]],


       [[[1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6],
         [1, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6

>In the above example, the array is repeated in 4-dimnesions unlike in the first example, where it was repeated only in 1-dimension

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
np.tile(np.array([1, 3, 5 ,6]) , reps=5.3)

TypeError: 'float' object cannot be interpreted as an integer

> The above error is generated due to the use of `float` type value for `reps` attribute, instead it should be `int` value.

> This function can be used when a particular array is to repeated a particular number of times.



## Function 5 - np.pad

It is used to pad an array

In [21]:
arr = np.array([[1,3, 4],[5,4,7],[1,4,6]])
arr

array([[1, 3, 4],
       [5, 4, 7],
       [1, 4, 6]])

In [22]:
# Example 1 - working
np.pad(arr, pad_width=2, mode='constant', constant_values = 0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 3, 4, 0, 0],
       [0, 0, 5, 4, 7, 0, 0],
       [0, 0, 1, 4, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

> In the above example, a border of $0's$ of width 2 is added to the following array. 

In [23]:
# Example 2 - working
np.pad(arr, (2,3) , 'wrap')

array([[4, 7, 5, 4, 7, 5, 4, 7],
       [4, 6, 1, 4, 6, 1, 4, 6],
       [3, 4, 1, 3, 4, 1, 3, 4],
       [4, 7, 5, 4, 7, 5, 4, 7],
       [4, 6, 1, 4, 6, 1, 4, 6],
       [3, 4, 1, 3, 4, 1, 3, 4],
       [4, 7, 5, 4, 7, 5, 4, 7],
       [4, 6, 1, 4, 6, 1, 4, 6]])

> In the above example, the first values are used to pad the end and the end values are used to pad the beginning.

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
np.pad(arr,(3,3,3), mode='constant', constant_values=0)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,)  and requested shape (2,2)

We got the `ValueError` because the original array was of `2-d` but on `np.pad` function we were requesting to create a `3-d` array.

So , when you want to pad an array you can always use `np.pad` function

## Conclusion

In this notebook, 5 functions of numpy are studied and experimented on different values. The functions are broken down to the cases where they show different types of errors and 